### ISSUE TITLE
Compiling problem.

### ISSUE THREAD

**Issue by ackcsaba** [Andoramb/Nextion-wall-mount#1]
Hello!

I try to compile yaml file, but I took an error message: **src/main.cpp:487:3: warning: multi-line comment [-Wcomment]
   //   lambda: !lambda "auto date=id(sntp_time).now().strftime(\"%b. %d\");\nauto time=id(sntp_time).now();\n\**

Please help me for solution.

Thanx
Csaba

**Comment by Andoramb** [comment]
Hi!
That shouldn't be a problem actually. Could you post the whole output?
Szívesen,
Andor

**Comment by Andoramb** [comment]
Could you sort it out? can I close this issue? 
Thanks

**Comment by ackcsaba** [comment]
Hello!

Igen, lezárhatod. Közben megoldódott.

Üdv
Csaba

Andoramb <notifications@github.com> ezt írta (időpont: 2020. aug. 26., Sze
21:00):
